### ISSUE TITLE
What to unit-test?

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/ui-forms#73]
I propose that this lib should, in the end, have:
- 100% coverage on the FieldAdapter as it contains logic that will be leveraged by many components.
- 100% coverage on all validators, parsers/formatters, because these functions are important and pure (so easy to test).
- Virtually all of the other components can do without tests, because in theory these should not contain any logic, but instead just be some (ui-core) imported component wrapped in the `FieldAdapter`.

**Comment by Mohammer5** [comment]
I'd like to introduce cypress tests here as well, and create test specific stories (like whole forms), so we can test integration of `ui-core` components with the `FieldAdapter` and `Final-Form` as well.

Regarding the unit tests:

> 100% coverage on the FieldAdapter as it contains logic that will be leveraged by many components.

> Virtually all of the other components can do without tests, because in theory these should not contain any logic, but instead just be some (ui-core) imported component wrapped in the FieldAdapter.

> 100% coverage on all validators, parsers/formatters, because these functions are important and pure (so easy to test).

I agree with all of these

**Comment by HendrikThePendric** [comment]
Closing this issue because we have settled this discussion
